'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { applicationStageLabels, getHrApplications, getHrCandidates, getManagedJobs, getManagedProjects } from '../lib/hr-store';
import type { Application, Candidate, Job, RecruitmentProject } from '../types/recruitment';

export default function HrCandidates() {
  const [applications, setApplications] = useState<Application[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [projects, setProjects] = useState<RecruitmentProject[]>([]); const [keyword, setKeyword] = useState(''); const [jobId, setJobId] = useState(''); const [projectId, setProjectId] = useState(''); const [stage, setStage] = useState(''); const [owner, setOwner] = useState('');
  useEffect(() => { const timer = window.setTimeout(() => { setApplications(getHrApplications()); setCandidates(getHrCandidates()); setJobs(getManagedJobs()); setProjects(getManagedProjects()); }, 0); return () => window.clearTimeout(timer); }, []);
  const rows = useMemo(() => applications.map((application) => ({ application, candidate: candidates.find((item) => item.candidate_id === application.candidate_id), job: jobs.find((item) => item.job_id === application.job_id), project: projects.find((item) => item.project_id === application.project_id) })).filter((row) => { const text = `${row.candidate?.name}${row.candidate?.phone}${row.candidate?.email}${row.candidate?.school}`.toLowerCase(); return (!keyword || text.includes(keyword.toLowerCase())) && (!jobId || row.application.job_id === jobId) && (!projectId || row.application.project_id === projectId) && (!stage || row.application.status === stage) && (!owner || row.application.owner_name === owner); }), [applications, candidates, jobs, projects, keyword, jobId, projectId, stage, owner]);
  const owners = [...new Set(applications.map((item) => item.owner_name))];
  return <><div className="hr-page-title"><div><p>APPLICATION PIPELINE</p><h1>候选人</h1><span>列表以 Application 为业务行，同一候选人的不同职位申请独立展示</span></div><strong className="hr-record-count">{rows.length} 条申请</strong></div><div className="hr-filter-bar"><label className="hr-search"><span>⌕</span><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="搜索姓名、手机号、邮箱、学校" /></label><label><span>职位</span><select value={jobId} onChange={(event) => setJobId(event.target.value)}><option value="">全部</option>{jobs.map((item) => <option value={item.job_id} key={item.job_id}>{item.title}</option>)}</select></label><label><span>招聘项目</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">全部</option>{projects.map((item) => <option value={item.project_id} key={item.project_id}>{item.project_name}</option>)}</select></label><label><span>招聘阶段</span><select value={stage} onChange={(event) => setStage(event.target.value)}><option value="">全部</option>{Object.entries(applicationStageLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>负责人</span><select value={owner} onChange={(event) => setOwner(event.target.value)}><option value="">全部</option>{owners.map((item) => <option key={item}>{item}</option>)}</select></label></div><div className="hr-table-wrap"><table className="hr-table candidate-table"><thead><tr><th>候选人</th><th>教育背景</th><th>应聘职位</th><th>招聘项目</th><th>当前阶段</th><th>投递 / 更新</th><th>负责人</th><th></th></tr></thead><tbody>{rows.map(({ application, candidate, job, project }) => <tr key={application.application_id}><td><strong>{candidate?.name}</strong><small>{candidate?.phone}</small></td><td><span>{candidate?.school}</span><small>{candidate?.highest_degree} · {candidate?.major}</small></td><td><strong>{job?.title}</strong><small>{job?.job_category}</small></td><td>{project?.project_name ?? '普通校园招聘'}</td><td><span className={`hr-stage stage-${application.status}`}>{applicationStageLabels[application.status]}</span></td><td><span>{new Date(application.applied_at).toLocaleDateString('zh-CN')}</span><small>{new Date(application.updated_at).toLocaleString('zh-CN')}</small></td><td>{application.owner_name}</td><td><Link href={`/hr/candidates/${application.application_id}`}>查看 ↗</Link></td></tr>)}</tbody></table>{!rows.length && <div className="hr-empty">暂无匹配的 Application</div>}</div></>;
}
