'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { getActivities, getHrApplications, getHrCandidates, getHrInterviews, getManagedJobs, getManagedProjects, applicationStageLabels } from '../lib/hr-store';
import type { Application, ApplicationActivity, Candidate, Interview, Job, RecruitmentProject } from '../types/recruitment';

export default function HrDashboard() {
  const [applications, setApplications] = useState<Application[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [interviews, setInterviews] = useState<Interview[]>([]); const [activities, setActivities] = useState<ApplicationActivity[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [projects, setProjects] = useState<RecruitmentProject[]>([]); const [ready, setReady] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { setApplications(getHrApplications()); setCandidates(getHrCandidates()); setInterviews(getHrInterviews()); setActivities(getActivities()); setJobs(getManagedJobs()); setProjects(getManagedProjects()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  const metrics = useMemo(() => { const today = new Date(); const day = today.getDay() || 7; const weekStart = new Date(today); weekStart.setHours(0, 0, 0, 0); weekStart.setDate(today.getDate() - day + 1); const weekEnd = new Date(weekStart); weekEnd.setDate(weekStart.getDate() + 7); return [{ label: '新投递', value: applications.filter((item) => item.status === 'new').length, tone: 'red' }, { label: '待筛选', value: applications.filter((item) => item.status === 'screening').length, tone: 'blue' }, { label: '待面试', value: interviews.filter((item) => item.status === 'pending').length, tone: 'orange' }, { label: '面试中', value: applications.filter((item) => ['first_interview', 'second_interview'].includes(item.status)).length, tone: 'violet' }, { label: '待 Offer', value: applications.filter((item) => item.status === 'offer').length, tone: 'green' }, { label: '本周面试', value: interviews.filter((item) => { const date = new Date(item.scheduled_at); return item.status === 'scheduled' && date >= weekStart && date < weekEnd; }).length, tone: 'navy' }]; }, [applications, interviews]);
  if (!ready) return <div className="hr-page-loading">正在计算招聘数据…</div>;
  const jobCounts = jobs.map((job) => ({ ...job, count: applications.filter((item) => item.job_id === job.job_id).length })); const projectCounts = projects.map((project) => ({ ...project, count: applications.filter((item) => item.project_id === project.project_id).length }));
  return <><div className="hr-page-title"><div><p>RECRUITING OVERVIEW</p><h1>招聘工作台</h1><span>基于当前 Application 与 Interview Mock 数据实时计算</span></div><Link className="hr-primary-button" href="/hr/candidates">查看候选人 <span>→</span></Link></div><div className="hr-metrics">{metrics.map((metric) => <article key={metric.label} className={`metric-${metric.tone}`}><span>{metric.label}</span><strong>{metric.value}</strong><small>APPLICATIONS</small></article>)}</div><div className="hr-dashboard-grid"><section className="hr-panel"><div className="hr-panel-title"><h2>各职位候选人数</h2><Link href="/hr/jobs">职位管理 ↗</Link></div><div className="count-list">{jobCounts.map((job) => <div key={job.job_id}><span><strong>{job.title}</strong><small>{job.job_category}</small></span><b>{job.count}</b></div>)}</div></section><section className="hr-panel"><div className="hr-panel-title"><h2>各招聘项目候选人数</h2><Link href="/hr/projects">项目管理 ↗</Link></div><div className="count-list">{projectCounts.map((project) => <div key={project.project_id}><span><strong>{project.project_name}</strong><small>{project.status_label}</small></span><b>{project.count}</b></div>)}</div></section><section className="hr-panel activity-panel"><div className="hr-panel-title"><h2>近期候选人动态</h2><span>{candidates.length} 位候选人 · {applications.length} 条申请</span></div><div className="recent-activities">{activities.slice(0, 6).map((activity) => { const application = applications.find((item) => item.application_id === activity.application_id); const candidate = candidates.find((item) => item.candidate_id === application?.candidate_id); return <Link href={`/hr/candidates/${activity.application_id}`} key={activity.activity_id}><span className="activity-dot"></span><div><strong>{candidate?.name ?? '候选人'} · {activity.description}</strong><small>{activity.operator} · {new Date(activity.created_at).toLocaleString('zh-CN')}</small></div><b>{application ? applicationStageLabels[application.status] : ''}</b></Link>; })}</div></section></div></>;
}
