'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { buildInterviewInvitePayload, getHrCandidates, getHrInterviews, getManagedJobs, INTERVIEW_INVITE_URL, updateInterviewStatus } from '../lib/hr-store';
import type { Candidate, Interview, Job } from '../types/recruitment';

const statusLabels = { pending: '待安排', scheduled: '已安排', completed: '已完成', cancelled: '已取消' } as const;
export default function HrInterviews() {
  const [interviews, setInterviews] = useState<Interview[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [status, setStatus] = useState(''); const [invite, setInvite] = useState<Interview | null>(null);
  function load() { setInterviews(getHrInterviews()); setCandidates(getHrCandidates()); setJobs(getManagedJobs()); }
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, []);
  const rows = useMemo(() => interviews.filter((item) => !status || item.status === status), [interviews, status]); const payload = invite ? buildInterviewInvitePayload(invite) : null;
  return <><div className="hr-page-title"><div><p>INTERVIEW OPERATIONS</p><h1>面试管理</h1><span>查看面试安排、更新状态并预览邀约接口参数</span></div></div><div className="interview-status-tabs"><button className={!status ? 'active' : ''} onClick={() => setStatus('')}>全部 <b>{interviews.length}</b></button>{Object.entries(statusLabels).map(([value, label]) => <button className={status === value ? 'active' : ''} onClick={() => setStatus(value)} key={value}>{label} <b>{interviews.filter((item) => item.status === value).length}</b></button>)}</div><div className="hr-table-wrap"><table className="hr-table interview-table"><thead><tr><th>候选人 / 职位</th><th>轮次</th><th>时间</th><th>面试官</th><th>形式 / 地点</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map((interview) => { const candidate = candidates.find((item) => item.candidate_id === interview.candidate_id); const job = jobs.find((item) => item.job_id === interview.job_id); return <tr key={interview.interview_id}><td><strong>{candidate?.name}</strong><small>{job?.title}</small></td><td>{interview.round}</td><td>{new Date(interview.scheduled_at).toLocaleString('zh-CN')}</td><td>{interview.interviewer}</td><td><span>{interview.meeting_type}</span><small>{interview.location}</small></td><td><span className={`interview-status interview-${interview.status}`}>{statusLabels[interview.status]}</span></td><td><div className="table-actions"><Link href={`/hr/candidates/${interview.application_id}`}>候选人</Link><button onClick={() => setInvite(interview)}>发送邀约</button>{interview.status === 'scheduled' && <button onClick={() => { updateInterviewStatus(interview.interview_id, 'completed'); load(); }}>完成</button>}</div></td></tr>; })}</tbody></table></div>{invite && payload && <div className="hr-drawer-backdrop" onMouseDown={() => setInvite(null)}><aside className="hr-drawer" onMouseDown={(event) => event.stopPropagation()}><button className="drawer-close" onClick={() => setInvite(null)}>×</button><div className="drawer-title"><p>INTERVIEW INVITATION</p><h2>发送面试邀约</h2><span>Mock 参数预览，不调用真实邀约系统。</span></div><div className="invite-config"><small>INTERVIEW_INVITE_URL</small><strong>{INTERVIEW_INVITE_URL || '未配置（Mock）'}</strong></div><pre className="invite-payload">{JSON.stringify(payload, null, 2)}</pre><button className="hr-primary-button" onClick={() => setInvite(null)}>模拟发送完成</button></aside></div>}</>;
}
